name: project_repository
description: The Repo that handles projects
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  file_repository:
    path: ../file_repository

  # utils
  rxdart: ^0.27.7
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true